project:
  type: website
  output-dir: docs

website:
  title: "Home"
  favicon: logo.png
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: people.qmd
        text: People
      - href: projects/index.qmd
        text: Projects
      - href: news/index.qmd
        text: News
      - href: contacts.qmd
        text: Contacts 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
