project:
  type: website
  output-dir: docs

website:
  site-url: "https://odeka-asbl.github.io"
  title: "<img src='odeka_logo.png' style='height: 30px; vertical-align: middle; margin-right: 8px;'><span style='color: black;vertical-align: middle;'>ODEKA</span>"
  favicon: /favicon.png
  navbar:
    left:
      - href: 01_about/about.qmd
        text: About us
      - href: 02_people/people.qmd
        text: People
      - href: 03_projects/index.qmd
        text: Projects
      - href: 04_news/index.qmd
        text: News
      - href: 05_jobs/index.qmd
        text: Jobs
      - href: 06_contacts/contacts.qmd
        text: Contacts
      - href: 07_legal_notice/legal_notice.qmd
        text: Legal Notice 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
